Consul Tags on Services
criteo/consul-bench pull request #5
Opened 2020-08-21 14:02 UTC by codyja

Hi,
Great project and very useful for load testing consul clusters! Thank you!

In this PR, I tried adding a new optional flag called `-tags` that will take a comma separated list of flags to add onto each service. 

We have some load balancers (Fabio and Traefik) that monitor services in consul looking for specific tags on services. Then these matched services get added as routes in the load balancers. To help us do a more real world load tests, we thought it would be great to more closely mimic our production consul clusters with the load balancers in the mix also watching services.

2020-08-21 16:15 UTC, pierresouchay commented
@codyja Still small error in Travis, ping us if you need help

2020-08-21 16:18 UTC, ShimmerGlass requested changes

2020-08-21 16:18 UTC, ShimmerGlass commented on service.go
> +		tagsSplit := strings.Split(serviceTags, ",")
You can remove the `for` and just do `tags = strings.Split(serviceTags, ",")`

2020-08-21 16:24 UTC, ShimmerGlass commented
Could you rebase your PR to fix the build issue ?

2020-08-21 18:30 UTC, codyja commented on service.go
> +		tagsSplit := strings.Split(serviceTags, ",")
Ah, that is much better and I understand why now too. Thanks

2020-08-21 18:31 UTC, codyja commented
I believe I rebased pulling in the latest changes, but I'm struggling to get past the build failure in travis for some reason still.

2020-08-21 19:31 UTC, codyja commented
@pierresouchay @ShimmerGlass , it took me a little while but it looks like that last build passed about a year ago on go 1.13. This latest build was trying to updated dependencies with that `-u` flag on `go get` and it was pulling in a consul package with some issues. Let me know if you think removing that `-u` flag was acceptable or not.

Also, should I do a git tag here also?

2020-08-22 09:10 UTC, ShimmerGlass commented
Thx for taking the time to debug this. Indeed, we shouldn't have a `go get -u` in the build I'm not sure how the go mod PR passed.
In fact, now that we are using modules `go get` is unnecessary.
I'll merge your PR and fix that on my end, as well as creating a new release.

2020-08-22 09:10 UTC, ShimmerGlass approved these changes

2020-08-22 09:11 UTC, merged

2020-08-25 22:17 UTC, codyja commented
Awesome, thank you much!